### PR TITLE
updated struct fields

### PR DESCRIPTION
**Pull request by sphinxc0re**

### CODE REVIEW

**Comment by TDHolmes** [comment]
@Helvethor any update?

**Comment by Helvethor** [comment]
I have not touched this thing for 2 years, please fork it :)

**Comment by TDHolmes** [comment]
Since this is the repo on crates.io and referenced as the rust binding for the c++ library, would you consider either adding some other folks as maintainers or transferring the crates.io repo elsewhere with other maintainers? I’d be down to help out.

**Comment by sphinxc0re** [comment]
I already started working on an automated bindings generator. Maybe we could put something together.

**Comment by TDHolmes** [comment]
@sphinxc0re I'm down! I opened some PRs on your fork, but if we could make something that more automatically updates as the C++ library changes that'd be good. One of my PRs is updating the struct definition **_again_**

**Comment by sphinxc0re** [comment]
I've completely automated the process of generating the low-level bindings to the c++ lib. Let me take a look where I left that code...

**Comment by sphinxc0re** [comment]
@Helvethor Would it be okay for you to hand over the crate if we manage to get a solid codebase going?

**Comment by Helvethor** [comment]
I sent you two an invite to become owner of the crate. I used your github usernames, I hope it works

**Pull request merged**
